---
 - name: Add ubuntu user to docker group.
   user:
     name: ubuntu
     groups: docker
     append: yes

 - name: Install Pip.
   apt: name=python-pip state=installed

 - name: Install Docker Python library.
   pip: name=docker-py state=present
